name: Run Tests

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: amd64-runner

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Read go version
        id: goversion
        run: echo "version=$(cat .go-version)" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ steps.goversion.outputs.version }}

      - name: Build go
        run: go build

      - name: Build Docker image
        run: make build

      - name: Build binaries
        run: make go-build-release
